export default [
    {title: 'ololo',
     id: 1},
    {title: 'tulula',
     id: 2},
    {title: 'beavis',
     id: 3},
    {title: 'butt-head',
     id: 4},
    {title: 'beavis',
     id: 5},
    {title: 'butt-head',
     id: 6},
    {title: 'butt-head',
     id: 7},
    {title: 'butt-head',
     id: 8},
    {title: 'butt-head',
     id: 9},
    {title: 'butt-head',
     id: 10},
]